### PR TITLE
Add sticky header for tables

### PR DESCRIPTION
**Pull request by smaximov**
This PR adds [sticky positioning](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning) for table headers. The intention is to make it easier to associate test results with SVG implementations, so it is no longer necessary to remember which table column corresponds to the particular implementation.

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Thanks! It's a good idea. I wanted to the same by myself, but I'm not good with the web stuff.

I run your PR locally (`bundle exec jekyll serve`) and it doesn't work. I'm using Chrome Version 66.0.3359.117

Am I missing something?

**Comment by smaximov** [comment]
Thanks for the catch, I tested it in Firefox only. I googled a bit and it seems like it's a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=702927) in Blink. I'll try to find a workaround for Chrome.

**Comment by RazrFalcon** [comment]
Thanks!

Also, the demo from the mozilla site actually works.

**Comment by smaximov** [comment]
Added workaround for Chrome, tested it on Chrome 65.0.3325.181 and Safari 11.1.

**Comment by RazrFalcon** [comment]
Thanks a lot!

**Pull request merged**
